apiVersion: v1
kind: Service
metadata:
  labels:
    app: myyoudep
  name: nodeport
spec:
  ports:
  - nodePort: 31196
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: my_you_dep
  type: NodePort
